// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "13359f7e-e821-46f7-a209-3c0a76618abb";

const char APPEUI[]   = SECRET_APP_EUI;
const char APPKEY[]   = SECRET_APP_KEY;


float freqx;
float freqy;
float freqz;
float humidity;
float phasex;
float phasey;
float phasez;

void initProperties(){
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(freqz, 1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(phasez, 2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(freqy, 3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(freqx, 4, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(phasey, 5, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(phasex, 6, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity, 7, READ, ON_CHANGE, NULL);
  
  

}

LoRaConnectionHandler ArduinoIoTPreferredConnection(APPEUI, APPKEY, _lora_band::AU915, "ff000001f000ffff00020000");
